# Generated by Django 5.1.4 on 2025-02-12 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catagories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='catagori',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='catagori',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
