# Generated by Django 5.1.4 on 2025-01-22 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='school',
            field=models.TextField(default='kako'),
        ),
    ]
